### ISSUE TITLE
QQ浏览器服务端本地调试

### ISSUE THREAD

**Issue by muzishuiji** [Panfen/wemovie#1]
我想请问下,你知不知道这个视频里讲的QQ浏览器服务端本地调试怎么开启啊?

**Comment by Panfen** [comment]
我没使用QQ浏览器，直接在手机端测试的

**Comment by muzishuiji** [comment]
那你是购买的服务器还是使用的ngrok服务器代理,使用代理好烦,莫名其妙就不行了.

**Comment by Panfen** [comment]
因为是写着玩的，也就没购买服务器了，使用的是localtunnel

**Comment by muzishuiji** [comment]
嗯嗯,好的吧,谢谢啦
